
 const map = [
  
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },

  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '1', status: false },
  { key: '' , status: false },
  { key: 'x', status: false },
  { key: 'x', status: false },
  { key: 'x', status: false },
  { key: 'x', status: false },
  { key: '' , status: false },
  { key: '2', status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },

  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '3', status: false },
  { key: '' , status: false },
  { key: 'x', status: false },
  { key: 'x', status: false },
  { key: 'x', status: false },
  { key: 'x', status: false },
  { key: '', status: false } ,
  { key: '4', status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },

  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },

  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '5', status: false },
  { key: '6', status: false },
  { key: '7', status: false },
  { key: '8', status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },

  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },

  { key: '' , status: false },
  { key: '' , status: false },
  { key: '9', status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '10', status: false },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '11', status: false },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '12', status: false },
  { key: '', status: false  },
  { key: '', status: false  },

  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },

  { key: '', status: false  },
  { key: '', status: false  },
  { key: '13', status: false },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '14', status: true },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '15', status: false },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '16', status: false },
  { key: '', status: false  },
  { key: '', status: false  },

  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },

  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },
  { key: '', status: false  },

  { key: '', status: false  },
  { key: '', status: false  },
  { key: '17', status: false },
  { key: '', status: false  },
  { key: '18', status: false },
  { key: '', status: false  },
  { key: 'x', status: false },
  { key: 'x', status: false },
  { key: '', status: false  },
  { key: '19', status: false },
  { key: '', status: false  },
  { key: '20', status: false },
  { key: '', status: false  },
  { key: '', status: false  },

  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: 'x', status: false },
  { key: 'x', status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },

  { key: '', status: false  },
  { key: '', status: false  },
  { key: '21', status: false },
  { key: '', status: false  },
  { key: '22', status: false },
  { key: '', status: false  },
  { key: 'x', status: false },
  { key: 'x', status: false },
  { key: '', status: false  },
  { key: '25', status: false },
  { key: '', status: false  },
  { key: '26', status: false },
  { key: '', status: false  },
  { key: '', status: false  },

  { key: '', status: false  },
  { key: '', status: false  },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: 'x', status: false },
  { key: 'x', status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },

  { key: '', status: false  },
  { key: '', status: false  },
  { key: '27', status: false },
  { key: '', status: false  },
  { key: '28', status: true },
  { key: '', status: false  },
  { key: 'x', status: false },
  { key: 'x', status: false },
  { key: '', status: false  },
  { key: '29', status: false },
  { key: '', status: false  },
  { key: '30', status: false },
  { key: '', status: false  },
  { key: '', status: false  },

  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: 'x', status: false },
  { key: 'x', status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },
  { key: '' , status: false },

  { key: '', status: false  },
  { key: '', status: false  },
  { key: '31', status: false },
  { key: '', status: false  },
  { key: '32', status: false },
  { key: '', status: false  },
  { key: 'x', status: false },
  { key: 'x', status: false },
  { key: '', status: false  },
  { key: '35', status: false },
  { key: '', status: false  },
  { key: '36', status: false },
  { key: '', status: false  },
  { key: '', status: false  },

];



export default (map);