
 export const map1 = (phone) => {
 
  return (
    [
  
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'1', type: '', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'2', type: '', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },

  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'3', type: '', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'empty', status: false } ,
  { table:'4', type: '', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'5', type: '', status: false },
  { table:'6', type: '', status: false },
  { table:'7', type: '', status: false },
  { table:'8', type: '', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'9', type: '', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'10', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'11', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'12', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'13', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'14', type: '', status: true },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'15', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'16', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'17', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'18', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'19', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'20', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'21', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'22', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'23', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'24', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

]
  );
};
 


  export const map2 = (phone) => {
 
  return ([
  
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'1', type: '', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'2', type: '', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },

  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'3', type: '', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'empty', status: false } ,
  { table:'4', type: '', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'5', type: '', status: false },
  { table:'6', type: '', status: false },
  { table:'7', type: '', status: false },
  { table:'8', type: '', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'9', type: '', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'10', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'11', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'12', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'13', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'14', type: '', status: true },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'15', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'16', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'17', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'18', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'19', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'20', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'21', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'22', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'23', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'24', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'25', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'26', type: '', status: true },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'27', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'28', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },
  { table:'', type: 'empty' , status: false },

  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },
  { table:'29', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'30', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'block', status: false },
  { table:'', type: 'block', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'31', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'32', type: '', status: false },
  { table:'', type: 'empty', status: false  },
  { table:'', type: 'empty', status: false  },

]);
  }